openapi: 3.1.0
info:
  version: 1.0.0
  title: AquaTrack
  license:
    name: Apache 2.0
    url: <http://www.apache.org/licenses/LICENSE-2.0.html>
  description: >
    An application with registration and login functionality that allows you to store information about the water you drink.
tags:
  - name: Users
    description: Users operations.
servers:
  - url: https://project6-back.onrender.com
paths:
  /users/registered-users:
    get:
      $ref: '../swagger/paths/users/getAllRegisteredUsers.yaml'
  /users/register:
    post:
      $ref: '../swagger/paths/users/register.yaml'
  /users/login:
    post:
      $ref: '../swagger/paths/users/login.yaml'
  /users/refresh:
    post:
      $ref: '../swagger/paths/users/refresh.yaml'
  /users/update:
    patch:
      $ref: '../swagger/paths/users/update.yaml'
  /users/current-user-data:
    get:
      $ref: '../swagger/paths/users/getCurrentUserData.yaml'
  /users/logout:
    post:
      $ref: '../swagger/paths/users/logout.yaml'
  /users/send-reset-email:
    post:
      $ref: '../swagger/paths/users/sendResetEmail.yaml'
  /users/reset-password:
    post:
      $ref: '../swagger/paths/users/resetPassword.yaml'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
